### PR TITLE
Log out sass error message.

### LINKED ISSUE #73: Compiling fails with [object Object]
Newer versions of node-sass return an object on error as opposed to just a message, resulting in stacktraces like this:
```
error: Compiling of 'app/styles/production.scss' failed. [object Object]
```

You can see a test where they expect this [here](https://github.com/sass/node-sass/blob/02d9cf96ff6019d74daf36bd8b4b734e2af3a7aa/test/api.js#L80) and note that [gulp-sass](https://github.com/dlmanning/gulp-sass/issues/170) also saw and resolved this issue.

### PR DESCRIPTION
**Pull request by blimmer**
NodeSass v2 now wraps the error message in an object.
This commit fixes #73

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ SassCompiler.prototype._nativeCompile = function(source, callback) {
       callback(null, data);
     }),
     error: (function(error) {
-      callback(error);
+      callback(error.message);
```
Comment (es128) [inline index.js]: `error.message || error` to preserve compatibility

Comment (es128) [inline index.js]: Could maybe even future-proof it a bit with `util.inspect`

Comment (blimmer) [inline index.js]: util.inspect isn't quite as readable, so I'll leave it up to you which you prefer:
```
12 Mar 16:15:46 - error: Compiling of 'app/styles/dev.scss' failed. { status: 1,
  file: 'app/styles/helpers/_functions.scss',
  line: 6,
  column: 11,
  message: 'argument `$map` of `map-get($map, $key)` must be a map\nBacktrace:\n\tapp/styles/helpers/_functions.scss:6, in function `map-get`\n\tapp/styles/helpers/_functions.scss:6, in function `palette`\n\tapp/styles/base/_bootstrap-override.scss:4',
  code: 1 }
```

Comment (es128) [inline index.js]: What I meant was `error.message || util.inspect(error)` in case of future unexpected changes so it won't break as badly as it did this time

Comment (blimmer) [inline index.js]: Got it, fixed.

**Comment by es128** [comment]
Thanks!

**Comment by blimmer** [comment]
Thanks for the fast merge. Do you think this is `1.8.10` worthy?

**Comment by es128** [comment]
Yes, but that isn't as easily accomplished from my phone. Ping me if I forget and don't do it sometime in the next 24hrs

**Comment by blimmer** [comment]
No problem.

On Thu, Mar 12, 2015 at 4:26 PM, Elan Shanker <notifications@github.com>
wrote:

> Yes, but that isn't as easily accomplished from my phone. Ping me if I
> forget and don't do it sometime in the next 24hrs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brunch/sass-brunch/pull/74#issuecomment-78657695>.
>



-- 
*Ben Limmer*
Software Developer
ben@ibotta.com
